In [1]:
# importing the libraries
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
# Importing the database
dataset = pd.read_csv('C://Users//hp//JupiterNobook_Files_For_ML//Datasets//Data.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [12]:
print(X)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [13]:
# taking care of missing data usng SI class we can replace missing salaries with average 
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan,strategy = 'mean')
# fit function helps to compute  using imputer class
imputer.fit(X[:,1:3])
# now we ahve to transform our data into readable data
X[:,1:3] = imputer.transform(X[:,1:3])

In [16]:
# encoding categorical data (Why - as if we have some data which are similar like names of countries then we need to change them in some rder machine can understand thats why we are dong categorical data change

In [17]:
# encoding the independant variables
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[0])], remainder ='passthrough')
X = np.array(ct.fit_transform(X))

In [18]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [33]:
# encoding the dependent varable
from sklearn.preprocessing  import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [35]:
# Splitting the data into trainng and test set
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test = train_test_split(X, y, test_size = 0.2, random_state = 1  )

In [40]:
# Feature Scaling -  when to apply before or after    
# we need to apply it after splitting   as our test set is something whch s raw and ths is a technique to apply n get Sd n mean for all values on test set.

#Main techniques Standardisation and normalisation
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,3:] = sc.fit_transform(X_train[:,3:])
X_test[:,3:] = sc.fit_transform(X_test[:,3:])

In [42]:
print(X_test)

[[0.0 1.0 0.0 -1.0 -1.0]
 [1.0 0.0 0.0 1.0 1.0]]
